numpy/numpy.org

NA-overview.rst
index.rst
old_array_packages.rst

While closing up bad links on `scipy.org` in <a href="https://github.com/scipy/scipy.org/pull/153">#153</a>, I ran into bad links on `numpy.org` as well.  I guess it's not too surprising since the last commit was made 3 (!) years ago!?

DOC: Updated old array package names + broken links via linkcheck

---

NA-overview.rst
_templates/sitenav.html
conf.py
index.rst
license.rst
old_array_packages.rst

Following the PR for the numpy docs (https://github.com/numpy/numpy/pull/8021) I also suggest to rename all instances of "Numpy" on the website to the official spelling "NumPy" (capital N and P).

rename Numpy -> NumPy

---

www/index.rst

As per the new spec, point to numpy.org/doc for archived documents and numpy.org/neps for neps
This still leaves the numpy org with 4 html repos (3 once we fold neps into devdocs) dedicated to github pages.
| Content repo | Trigger | Destination Repo | Web link | Notes |
|---|---|---|---|---|
| numpy.org | Merge to `master` | numpy.github.com | https://numpy.org/ |
| numpy | Merge to `master` | devdocs | https://numpy.org/devdocs |
| numpy | Merge to `master` | neps | https://numpy.org/neps | Can be folded into devdocs |
| numpy | Manual release step | doc | https://numpy.org/doc | Now the canonical home of docu- mentation archive|

point doc archive to numpy.org

---

www/conf.py

add link back to main page (instead of scipy.org)

---

config.yaml

And we're live: https://twitter.com/numpy_team
No tweets yet, will fix that before we launch the website, as well as set up access for other people and some kind of guideline on what we tweet (Dask just figured that out, we can copy from them).

Update Twitter handle to `numpy_team`

---

config.yaml

Swapped "Learn" and "Array computing" buttons in the top nav bar to match the approved site map.

Swap "Learn" and "Array computing" buttons in the top nav bar

---

layouts/partials/tabs.html

I had too much trouble figuring out what should go in that tab,
which is a sign that it probably shouldn't exist.

Remove "general purpose" tab

---

content/en/community.md

Fixing the link to the new Twitter account numpy_team.

Fix the link to the new Twitter account

---

scripts/fetch-ehtim.sh
scripts/numpy-ehtim-dep-graph.sh

This is for the black hole case study. Created by Shaloo in gh-23,
it got lost when we renamed `master` to `old-sphinx-site`.

Recover script to create the EHT imaging dependency graph

---

config.yaml
content/en/community.md
content/en/gethelp.md
layouts/partials/single/content.html

Closes gh-28. Also fixes some broken links to "Get Help".

Finish content on Get Help and Community pages.

---

static/css/section2.css
static/css/section3.css

Fixes gh-168 partially
I changed the positions of key feature and case studies for screen widths larger than 1280px. This example is in 2560 x 1440.
@joelachance said that he will re-arrange the NumPy title/CTA & the shell, so they'll be more centered.
If the white space between the the nav bar and key feature section is still there once Joel is done, I'll see if I can remove it.
Let me know of any suggestions or changes.

Change styling for high-resolution screens

---

config.yaml

Hugo 0.60 changes the default for raw html in Markdown files, see https://gohugo.io/news/0.60.0-relnotes/.  This fix follows the recommendation in those release notes.

Fix disappeared blockquotes in case studies.

---

config.yaml
layouts/partials/hero-body.html

We have no dedicated "Get started" page. I looked at some other projects, some link to install procedures, some to a quickstart or similar. For now I thought linking to the `Learn` page is most appropriate. That has the (not so great) quickstart guide in the Sphinx docs, an install link, and a bunch of other resources.

Make "Get started" button link work

---

layouts/partials/shell-content.html
layouts/partials/shell-lesson.html
static/css/shell.css

Note that the styling for this needs fixing in `shell.css`, now nothing is visible. I tried with the `shell-content-message` class and got:
So the highlighting is fine, but the text justification is messed up. @joelachance could you help with that?
Closes gh-81

Add content for the lesson displayed when the shell is active.

---

config.yaml

Deleted a link to the non-existing Trademarks page, moved the link to Code of conduct in its place for visual balance.

Reorganize the links in the footer

---

config.yaml

Fixing the link to NumPy documentation. The correct link is https://numpy.org/doc/

Fix the link to NumPy documentation

---

config.yaml
layouts/partials/footer.html
static/css/section2.css
static/css/tabs.css

Increased contrast ratio between words and background by changing the color of links in the Key Features, Ecosystem sections and footer.
This meets the contrast ratio a WCGA AA rating. Web Content Accessibility Guidelines and its rating range from A to AAA.
I used WebAIM and WAVE tools to check the rating.
**Questions**
I used ! important in the internal css to override external linked css from UiKit. I know ! important isn't generally recommended but it's how I was able to override the external css. **Does anyone know another way or is using ! important here OK?**
**Can I remove the empty h3 tag in footer.html and empty title in config.yaml?** Or is there a title planned for these sections?

Web accessibility - Contrast ratio for WCGA AA

---

layouts/_default/list.html

Quiets this `hugo server` warning: `found no layout file for "HTML" for "section"`

adds list.html to quiet hugo server warning.

---

static/css/styles.css

Not a ticket, but I like this style for nav rollover a bit better. Previously we had the 'hugo-fresh' orange with underline. This removes the underline and updates the rollover color to the lighter NumPy blue. Open to suggestions!

Removes underline on nav link hover, updates hover color

---

README.md
static/css/section2.css
static/css/section3.css
static/css/shell.css
static/css/styles.css
static/css/tabs.css

Updates colors to the ones from @InessaPawson in #48.
Colors are notated in styles.css and README.md
Review, and see what everyone thinks! LGTM.

[WIP] Updates colors to only colors in the NumPy color palette

---

content/en/case-studies/blackhole-image.md

A few suggestions for the EHT-imaging case study based on my comments in #175 .
I tried to make the commits relatively fine-grained so that individual changes can be reverted as you see fit. The main themes of these changes are:
1. Try to communicate some of the concepts with more precise language
2. Try to tighten the focus on NumPy and the role played in generating the black hole image.
I had one additional thought on the last graphic, i.e. the one captioned "Key NumPy Capabilities Used". To me, the caption is a bit out of sync with the image itself, which focuses a bit more on some specific technical challenges faced by the EHT team. I think the figure could have a more numpy-centric theme. For example, you could consider the following categories/descriptions:
**Flexibility** -> …

DOC: EHT Case Study Suggestions

---

content/en/case-studies/cricket-analytics.md

http://numpy-<pr_number>.surge.sh/

Fixes minor typos and grammar ref pull request 174

---

config.yaml
layouts/index.html
layouts/partials/css.html
layouts/partials/news.html
static/css/news.css

Resolves #219.
@InessaPawson, I wasn't sure about layout here. Do you have an example we should emulate?
I'm assuming we might tackle content in another ticket.

Adds a news section

---

config.yaml
content/en/news.md
layouts/partials/news.html
static/css/news.css

Changes to the news element on the front page:
- Make both title and text link to `/news`
- Tweak the text for v.1.18.0
This is what the news page looks like:

Add a News page

---

README.md

Instructs user to install the extended version of Hugo; points to the
Hugo install page and the release page; shows the error message
you'll get from the standard version.
http://numpy-<pr_number>.surge.sh/

DOC: Fix Hugo install instructions in README (issue #231)

---

config.yaml

Rewording for gravitational waves caption

---

layouts/partials/array-libraries.html
layouts/partials/data-science.html
layouts/partials/machine-learning.html
layouts/partials/scientific-domains.html
layouts/partials/visualization.html

Puts NumPy in the opening sentence of each Ecosystem section,
closing issue #235.
Reduces text in the Visualization section, addressing @rgommers's concern in issue #238.
Closes gh-235.

DOC: Emphasize NumPy in Ecosystem openers

---

config.yaml

Leave the content for now - it needs work, but is still valuable. This content is also connected to the "Array libraries" tab on the front page.

Hide the "array computing" page in the navbar

---

content/en/gethelp.md

Since visitors may want either user or developer help, I made the developer link more prominent.
Also, for Stack Overflow, added a link explaining how to tag a question.
Fixes gh-252

DOC: Make 'dev issues' more prominent in help page

---

layouts/partials/data-science.html

Follow up to gh-242, alternative to gh-262. The content rewrite and inclusion of more relevant libraries attempts to make this sound natural, sketch the breadth of the Python data science offerings,
and keeps some of the tools like DVC and MLFlow that beginning to intermediate data scientists really need to learn about.
It does shrink the amount of content to a more reasonable size:

Update content of Data Science tab

---

content/en/learn.md

Adds a prominent link to the NumPy docs and clearly describes the remainder of the
page as external.
Adds a link to the contribution info at bottom and gives it a heading.
**This page is still named `learn.md`!**  Someone will need to make the plumbing changes for this to become the Documentation page.
Addresses part of issue #235.

DOC: Integrate Learn and Documentation pages

---

content/en/about.md
content/en/arraycomputing.md
content/en/case-studies/blackhole-image.md
content/en/case-studies/cricket-analytics.md
content/en/case-studies/gw-discov.md
content/en/citing-numpy.md
content/en/code-of-conduct.md
content/en/installing-python-and-numpy-guide.md
content/en/learn.md
content/en/news.md
content/en/press-kit.md
static/gallery/team.html

1. Fixed grammar errors.
2. Addressed #237 ( Closes #237 ).
3. Replaced “she” with singular “they”.
4. Checked all the links.

Final review of the content

---

config.yaml
content/en/learn.md
layouts/partials/shell-content.html

The numpy.org/doc is a pretty useless page that we will get rid of in the future. The doc/stable link is new, and will keep pointing to the docs of the latest NumPy release. So let's use that.

Make "Documentation" link to numpy.org/doc/stable

---

content/en/learn.md
layouts/partials/data-science.html

Follow up to gh-272 and gh-258

Some last minor tweaks to textual things

---

layouts/partials/data-science.html

Minor one-word change, dropping the word "production":
>  Stable production deployments rely on
If we say "deployments" we don't need "production."

DOC: Drop unneeded word from Ecosystem->Data Science

---

static/css/news.css

Thanks @InessaPawson for the suggestion. I agree it looks better. 
Before:
After:

Minor tweak between title and text in news bar

---

config.yaml

Suggestion by @InessaPawson, now that the install page has way more content.
Okay one more. Ref gh-233, `Get Started` button.

Make the Get Started button point to the Install page

---

config.yaml

This shows up at least in Slack when you simple use the link to the
site, and it didn't look pretty. Maybe this needs another change,
but for now this will do.

Update the meta description of the site

---

layouts/partials/scientific-domains.html
layouts/partials/visualization.html

IPython, PyQuil, HoloViz can be accessed over https. QuTiP, scikit-bio, VisPy have invalid certificates.

ecosystem: update URLs to https

---

layouts/partials/scientific-domains.html

The `Quantum Computing` column in `scientific-domains.html` misses Qiskit, a leader in Quantum Computing software that heavily relies on NumPy.
To support this, here are some numbers comparing the main repository for each of the projects under `Quantum Computing`:
| Repository | Used by  | Watches | Stars | Forks |
| ---------- | ---------- | ---------- | ---------- | ---------- |
| https://github.com/rigetti/pyquil  | 100  | 82 | 1K | 279
| https://github.com/qutip/qutip  | 96 | 72 | 841 | 354 |
| https://github.com/Qiskit/qiskit-terra/ | 158 | 235 | 2.8K | 1.1K |

Add Qiskit to Quantum Computing column in scientific-domains.html

---

content/en/about.md

Per announcement in https://mail.python.org/pipermail/numpy-discussion/2020-June/080760.html.
Partial overlap with dev/governance/people.html in the numpy/numpy repo
(see PR #16757).

DOC: Add Matti Picus to steering council in new website

---

config.yaml
content/en/news.md

Add three news entries, put survey on the front page (it's still running for a week):

Add news entries on 1.19.0, the new logo and the survey

---

crowdin.yml

The case studies weren't showing up in Crowdin, this should fix it.
Format as in https://support.crowdin.com/configuration-file/#writing-a-simple-configuration-file

Update crowdin.yml for case studies being in a sub-folder

---

layouts/partials/scientific-domains.html

The Mathematical Analysis column in scientific-domains.html had an incorrect link to FEniCS.
I have fixed that.

Add correct link to FEniCS in scientific-domains.html

---

static/css/tabs.css

Closes gh-236.
This may help the reader discover the tabs slightly more easily, as suggested in gh-236. I'm not sure of impact on overall styling (e.g. mobile), so I won't self-merge this.

Slightly increase font size of titles of tabs on front page

---

static/gallery/team.html

Puts my name on the team page; currently has just my GitHub id, as explained in https://github.com/numpy/numpy.org/pull/351#issuecomment-671084374
This html file will be overwritten when the page is regenerated, but because I've now added my name to GitHub, the change will be in the new page as well.

DOC: Give bjnath's name on team page

---

Makefile

replaces #289 
This is based on the assumption that we still want a deploy workflow based on a local repo, not automated via CI.
The Makefile now has grown a few more options. The normal workflow would be `make clean; make html; make serve`, look at the local version or commit the changes and look at them via netlify. When a PR is merged to master,  `git checkout master; git pull; make serve`, look one more time, then `make deploy`. The pages will be put into a gh-pages branch and served via github pages from that branch.
Additionally, if you want to work on a fork, you can do all of the above with
`make TARGET=myname BASEURL=https://myname.github.io/numpy.org <command>`
which will deploy the pages to your fork, like [this](https://mattip.github.io/numpy.org/). It does take ~5 minutes for …

deploy via gh-pages

---

config.yaml

We didn't have v1.19.0 in the news bar yet, and it seems like the most suitable thing to put in now.

Update title bar after closing of the Survey

---

static/css/keyfeatures.css

@joelachance The white space in the “Key Features” section should be minimized. I’d like to hear your feedback on the proposed solution.

Homepage - remove the excess whitespace

---

content/en/diversity_sep2020.md
content/en/news.md

Also adds a short News entry about the Nature paper.
Already up at https://numpy.org/diversity_sep2020/ (it was thoroughly reviewed outside of GitHub), so merging straight away.

Add NumPy Diversity and Inclusion Statement

---

content/en/install.md

Give the Install page a pointer to the [Troubleshooting ImportError page](https://numpy.org/doc/stable/user/troubleshooting-importerror.html) in the Sphinx docs.

DOC: Add ImportError link for Install page

---

content/en/contribute.md

Noticed lots of people get in touch without any cultural context, so things like what to expect or how to ask questions are useful to have in a general guide. This link is the best guide I know of.

Add a link to opensource.guide/contribute on Contribute page

---

content/en/install.md

This is a continuation of gh-298. It takes over some changes from that PR, and adds new content based on review suggestions there.
- add using virtual environments to install commands in main section
- edit reproducible installs section
- update pip/conda and MKL/OpenBLAS parts
- clean up section headers and sidebar

Install page update

---

.github/workflows/gh-pages.yml

This action uses [GitHub Actions for GitHub Pages](https://github.com/peaceiris/actions-gh-pages) to deploy to the `gh-pages` branch, using mostly the examples in that repo's readme.
This works only on the master branch. The `gh-pages.yml` config should fetch our submodules, install `0.74.3/extended`, build, and update the `gh-pages` branch.
This is supposed to work 'out of the box' with the `GITHUB_TOKEN` token-- the docs mention this is created by the Github Actions runner.
@mattip @rgommers let me know if I'm missing anything here, happy to update this pr!

Create Github Actions

---

static/css/content.css

Fixes #375.
This appears to work fine with the other content pages in both mobile and desktop. This enables scrolling in the code blocks, so while you have to scroll to see the overflowing code content, the rest of the page is viewable.

Add overflow: auto to .content-container to fix install page

---

.github/workflows/gh-pages.yml

Reverts numpy/numpy.org#379
See https://github.com/numpy/numpy.github.com/pull/1

Revert "Add CNAME during deployment to gh-pages"

---

.github/workflows/gh-pages.yml

Resolves #384.
Update Github Action to use the new `chabad360/hugo-gh-pages` version. This allows us to push the build to a different repository.
This hasn't been tested as it's set up for master.

Update Github Action

---

.github/workflows/gh-pages.yml

Remove ticks around hugoVersion, re-arranges values to match the docs

Re-arrange Github Actions yaml

---

.github/workflows/gh-pages.yml

This was a bug, would have broken the deploy.

Ensure the new GitHub Action adds CNAME

---

README.md

Specifying RGB values in the docs regarding the NumPy website color palette. Partially fixes #numpygh-398 numpy/numpy.org#398.

Specify RGB values in the docs regarding the NumPy website color palette

---

config.yaml

Add a link to https://numpy.org/citing-numpy/ in the footer. Fixes #406
_Note:_ All the pages linked in the footer that could be possibly replaced are in the top 20 for page views (total and unique) according to Google Analytics. Hence, the proposed solution.

Add a link to numpy.org/citing-numpy/ in the footer

---

content/en/learn.md

Hi all, this adds a link to the [NumPy tutorials](https://numpy.org/numpy-tutorials) page to the Learn section of the website. Let me know what you think about the text and formatting. Thanks!

Added link to numpy-tutorials

---

static/css/keyfeatures.css

Resolves #417.
Adds additional space for 'key features' boxes on the home page. Also adds a fade for expanded content as shown here:

Add space for key features titles

---

content/en/config.yaml
content/en/news.md

Updating the news bar on the home page and news.md to announce the release of the 2020 NumPy survey findings.

Add the news about the 2020 NumPy survey results

---

content/en/about.md

This PR adds information about institutional partners and the NumFOCUS subcommittee, with the goal of unifying the governance pages about people (currently, almost identical content appears in [the Sphinx documentation](https://numpy.org/devdocs/dev/governance/people.html) and [the About Us page](https://numpy.org/about/). 
If this PR is accepted, we can eliminate the page in the Sphinx docs.
Partially addresses numpy/numpy#17496

Add content from Sphinx docs to unify governance pages

---

content/en/config.yaml
content/en/news.md

Making an announcement about the 2021 NumPy survey.

Make an announcement about the 2021 NumPy survey

---

content/en/citing-numpy.md
content/ja/citing-numpy.md
content/pt/citing-numpy.md

This PR changes the displayed DOI in `en` and `pt` localization of citing-numpy.md (a '1' was missing while the link was correct).
In the `ja` translation, additionally, a space is removed from the DOI link.

Fix displayed DOI in citing-numpy.md

---

LICENSE

I couldn't find what license the website content and theme was released under.  If I missed it, please let me know.  If not, this PR adds a revised BSD license to the repo.

Release website under BSD license

---

content/en/about.md
content/en/config.yaml
content/en/press-kit.md
content/ja/about.md
content/ja/config.yaml
content/ja/press-kit.md
content/pt/about.md
content/pt/config.yaml
content/pt/press-kit.md

This replaces
- `github.com/numpy/numpy/tree/master/` with `github.com/numpy/numpy/tree/main/`
and
- `github.com/numpy/numpy/blob/master/` with `github.com/numpy/numpy/blob/main/`
This reflects the change from `master` to `main` as the name of the default branch.

Update default NumPy branch

---

content/en/tabcontents.yaml
content/ja/tabcontents.yaml
content/pt/tabcontents.yaml

Replaced http://vispy.org/gallery.html to https://vispy.org/gallery/index.html

Fixed broken link to the VisPy gallery

---

.gitignore
assets/css/mailchimp.css

In https://github.com/scientific-python/scientific-python-hugo-theme/pull/48, @stefanv removed some styling for the numpy.org mailchimp signup box.  This updates the theme and adds the mailchimp box styling to numpy.org.
I want to double-check with @stefanv about whether I have to include these lines:
```
$colorPrimaryDark: rgb(1, 50, 67);
$colorPrimaryLight: rgb(238, 238, 238); 
```
or if I can access them from `theme/scientific-python-hugo-theme/assets/sass/styles.scss`.

Restore mailchip css

---

content/en/about.md
scripts/gallery/team.md

1. Updating the link to the list of the Steering Council members on team.html 
Fixes #numpygh-503
2. Adding the survey team to the list of the existing NumPy teams on about.md
3. Making some very minor changes to the wording in the Teams section on about.md

Update info about NumPy teams

---

content/en/contribute.md

Add to contribute.md a link to the NumPy YouTube channel, specifically to the playlist titled "Contributing to NumPy: Getting Started".
Closes https://github.com/numpy/numpy.org/issues/533.

Add a link to the NumPy YouTube channel

---

content/en/learn.md

This PR  reflects a new policy on including educational content to learn.md. To stay consistent with the values of our project, from now on we will only list the content developed by NumPy contributors and vetted by the community.
I also moved info about the NumPy Tutorials to the Beginners and Advanced sections as it is more fitting with the structure of the page. The decision was discussed with @melissawm and @rossbar who were leading the Tutorials project.

Update content of learn.md to reflect a new policy

---

layouts/_default/baseof.html
layouts/partials/meta.html

Support for google analytics is no longer provided by the theme.  Since numpy.org will continue using google analytics (at least temporarily see #546), I am adding the old theme layout to the numpy.org repo.  If numpy.org decides to stop using google analytics, the following files
```
layouts/_default/baseof.html
layouts/partials/meta.html
```
should be deleted as well as this line
```
googleAnalytics: UA-162151853-1
```
in `config.yaml.in`.

Support google analytics

---

README.md
config.yaml.in

Trying plausible analytics.  We are using this for scipy.org, docs.scipy.org, and scientific-python.org.  If this PR is merged, you will be able to view the analytics for numpy.org at https://views.scientific-python.org/numpy.org.  The page is currently private, so you will need to create a plausible account and let @stefanv or me know what address you registered.
I don't know who currently has access to the google analytics, but we should make sure whoever is currently monitoring the google analytics is OK with using plausible.

Use plausible analytics

---

assets/css/shell.css
content/en/config.yaml
content/ja/config.yaml
content/pt/config.yaml
layouts/partials/shell.html
static/css/shell.css
static/js/app.js

Follow-up to #547 and #556 
JupyterLite now ships with the `repl` app by default:
- Added in: https://github.com/jupyterlite/jupyterlite/pull/498
- Documentation: https://jupyterlite.readthedocs.io/en/latest/applications/repl.html
- Changelog: https://github.com/jupyterlite/jupyterlite/releases/tag/v0.1.0a23
This PR updates the "Try NumPy" section:
https://user-images.githubusercontent.com/591645/154056572-4675b611-00c0-4488-b8b7-99d2ece07215.mp4
---
A follow-up to this would be to start making a custom JupyterLite deployment that can then be hosted in the `numpy` GitHub organization, for example at https://github.com/numpy/try or https://github.com/numpy/jupyterlite-repl.
The custom deployment can easily be done using this template repo: https://github.com/jupyterlite/demo

Switch to the upstream JupyterLite REPL app

---

Makefile
content/en/teams.md
content/ja/teams.md
content/pt/teams.md
static/gallery/docs-team.html
static/gallery/maintainers.html

Add docs team to gallery

---

assets/css/shell.css
layouts/partials/shell.html

This improves the alignment of the code console with respect to the example snipet
**Before:**
**After:**

Improve JupyterLite console alignment

---

content/en/code-of-conduct.md

Fixes gh-595
Using the link provided on the SciPy Community page: 
https://scipy.org/community/

Fix link to SciPy Code of Conduct in Numpy Code of Conduct

---

assets/css/vars-override.css

Fixes gh-497
Many links were colored #1e87f0 - updated them to match the Numpy color palette by coloring them #4D77CF (Numpy Deep Blue)

Updated link colors to NumPy Deep Blue #497

---

content/en/about.md
content/ja/about.md
content/pt/about.md

~- Updated the order of names in the `en/about` page to be in alphabetical order (as promised by the page)~
- Clarified the ordering of names
- Updated the names and order of `{ja,pt}/about` pages

DOC: Update ordering details and some translations

---

content/en/community.md

Fix: https://github.com/numpy/numpy.org/issues/436
Description:
The Community Calendar link which can be used to track all upcoming NumPy events is added to the Community section of the website.

Added Community Calendar link under Community section

---

assets/css/tabs.css
layouts/partials/array-libraries.html

Fixes [gh-489](https://github.com/numpy/numpy.org/issues/489#issue-1036065739)
The logos on the array libraries tab have different sizes, here they have a standard size (that might be changed, for example if reduced logos would be even more uniform).
Before:
After:

Standard size of logos in array libraries tab

---

content/en/config.yaml

Move the 'Open Source' key feature to a more visible place on the homepage.

Move the 'Open Source' key feature

---

content/en/config.yaml

I propose this UI change based on the discussion at the 2023-02-15 community call. See the meeting notes here: https://github.com/numpy/archive/blob/main/community_meetings/community-2023-02-15.md.

Add the latest release info to the homepage

---

content/en/tabcontents.yaml
static/images/content_images/arlib/awkward.svg

Fixes gh-632. This PR adds Awkward Array to the list of array libraries on NumPy's homepage, above uarray and tensorly, replacing XND, as recommended by @rgommers in https://github.com/numpy/numpy.org/issues/632#issuecomment-1468648585.

Add Awkward Array to list of other/external array libraries.

---

content/en/about.md

- Update info about the current NumPy teams and institutional partners.
- Rephrase for clarity some parts of the text.

Update info about the current NumPy teams and institutional partners

---

content/en/news.md

announce the NumPy 1.25.0 release

---

content/en/config.yaml
content/en/news.md

1. Announce NumPy 1.25 on homepage.
2. Minor fixes in the news article about the release.

Announce NumPy 1.25 on homepage

---

content/en/install.md

This PR adds an anchor before the **Reproducible installs** heading in `install.md`. This will allow the internal link to this section work for translated content.
See https://github.com/numpy/numpy.org/issues/55#issuecomment-1599175991
Previously, anchors were added just to the translated content in gh-540, but when translations need to be updated, these will be stripped by Crowdin if the anchor does not appear in the English content.

Make internal link work for translated content

---

content/en/news.md

This PR adds an explicit anchor to the releases section of `news.md`. This is required for the link to work with translated content.
cc @rgommers @melissawm

Add an explicit anchor to releases section

---

content/ja/news.md
content/pt/news.md

This PR adds Japanese and Portuguese translations to `news.md` for NumPy version 1.25.2. Manual updates to add translations for release lines will become unnecessary once gh-654 gets in.

Add translations for new numpy release line in news.md

---

.github/workflows/gh-pages.yml

Use GitHub's new deploy action mechanism, getting rid of the action that relies on an Alpine Docker image, causing trouble with Hugo.

Update GH pages workflow to not depend on external action

---

config.yaml.in
content/en/news.md
content/ja/news.md
content/pt/config.yaml
content/pt/news.md

Japanese and Portuguese translations have been completed and validated. This PR comments out the `disableLanguages` line in `config.yaml.in`. Once merged, this PR will make the Japanese and Portuguese translations available on numpy.org. On the desktop version of the page, a small drop-down for selecting the language will become available in the header:
On mobile, options to select the language will be added to the hamburger menu:
Japanese and Portuguese translations will be available at the URLs numpy.org/ja and numpy.org/pt respectively.
For ease of synchronization, I think the updates to `news.md`  to announce the new translations should be made in this PR in English, Japanese, and Portuguese simultaneously.
cc @rgommers, @melissawm, @InessaPawson, @AtsushiSakai

Publish Japanese and Portuguese translations to main website.

---

content/en/news.md
content/ja/news.md
content/pt/news.md

This PR updates the date in the header for news.md to today's date for English, Japanese, and Portuguese.

Update date in news.md header to today's date

---

content/ja/news.md
content/pt/news.md

This PR fixes newsLink for news.md to point to the correct languages. Currently the link below:
points to the English language news page regardless of language selected.

Fix broken newsLinks for Portuguese and Japanese

---

content/en/tabcontents.yaml

"Astronomy Processes" sounds extremely weird, I would suggest to drop the "Processes" part.

DOC: remove Processes from astronomy

---

assets/css/tabs.css

The Scientific Domain tab in the home page has overlapping text for the Japanese version (and also for the English version on mobile). These changes prevents overlap but are not responsive on mobile.
Before, on desktop:
After:

Fix overlap in text for Japanese translation

---

crowdin.yml

This PR changes `update_option` in `crowdin.yml` to `update_as_unapproved` in all cases. This makes it so when a source string changes, the translation is not lost, it only becomes unapproved. We have had an issue where changes in the structure of a page, or additions of news items, to cause Crowdin to think source strings have changed when that is not really the case. In the past I have gone through and manually added translations back, but then the information about who first added the translation is lost. With the new option, someone can go check if the strings have actually changed or not, and approve them if they have not without having to involve the translators, and while preserving who originally made the contributions.
See the  [Crowdin …

Set crowdin update_option to update_as_unapproved

---

content/en/config.yaml
content/ja/config.yaml
content/pt/config.yaml

Fixes numpy/numpy#24744. Note the news fragment is out of sync: the English one highlights the 1.26 release where the Japanese and Portuguese still have an older news fragment.

update latest release button in all languages

---

Makefile

This rule does not touch submodules, which allows the site to be served with a different commit in a submodule.  It also sets a couple of Hugo options which make the server's automatic rebuilding and refreshing more reliable.  (See <https://github.com/gohugoio/hugo/issues/10893>.)
https://github.com/numpy/numpy.org/pull/526 is also relevant, but unless and until that PR is advanced, the simple change in this PR provides a necessary enhancement for working with the numpy.org source code as the theme is being developed.
Thanks.

Meta: (Makefile) Add serve-dev rule

---

assets/css/tabs.scss
content/en/tabcontents.yaml
layouts/partials/scientific-domains.html

This refactors the "Ecosystem/Scientific Domains" tab on the front page:
- All links are defined in the configuration file rather than being half defined in the config file and half in the HTML template.
- The HTML is fully generated from the template according to the defined links.
- The generated HTML on the tab is responsive to various viewport sizes (it no longer uses hard-coded HTML tables).
Please note that this PR depends on https://github.com/scientific-python/scientific-python-hugo-theme/pull/434.  This PR should be merged to the numpy.org repo after that one is merged into the SPHT theme and the theme submodule is updated in the numpy.org repo accordingly.  Until then, this PR will fail CI.
This PR should fix https://github.com/numpy/numpy.org/issues/705.
I don't have …

Refactor "Ecosystem/Scientific Domains" tab on front page

---

content/en/about.md
content/ja/about.md
content/pt/about.md

On March 22nd, 2023, Melissa nominated me to join the NumFOCUS Subcommittee in her place via the NumPy Steering Council mailing list. I accepted the nomination and have been performing my duties for the past 9 months. This PR reflects the change in the Subcommittee membership.

NumFOCUS Subcommittee update

---

content/pt/about.md
content/pt/config.yaml
content/pt/news.md
content/pt/tabcontents.yaml

This PR adds recent updates made to the Portuguese translations. Similar to gh-698, to handle lack of synchrony between Crowdin and the actually published translations, I did a scripted rebase which filtered to just portuguese commits, and squashed all commits together which had touched the same file. I then rebased on main and manually fixed the merge conflicts. @melissawm, please let me know if everything looks OK.
Also, it appears XND has been replaced by Awkward Array in the list of dependent projects in the table of contents. The description "Manipulate JSON-like data with NumPy-like idioms." is currently untranslated.

L10n pt updates 2023 11 17

---

content/en/news.md

Changing info in the news bar on the home page to the announcement about the 1.26 release since the NF EOY fundraiser ended on Dec 23, 2023.

Update news bar to point to latest feature release again

---

content/en/gethelp.md

Removes Gitter and IRC from gethelp.md
Resolves https://github.com/numpy/numpy.org/issues/700

Remove Gitter and IRC from gethelp.md

---

content/en/_index.md
content/ja/_index.md
content/pt/_index.md

@steppi @rgommers Switching to the new grid syntax.
v0.13 
- add new syntax via grid1 to theme
- port website to grid1
v0.14
- cp grid1 to grid in theme
- replace grid1 with grid in websites
v0.15
- rm grid1 from theme
- nothing to do for websites

Use new grid syntax

---

content/en/tabcontents.yaml
layouts/partials/tabs.html

Add the HyperSpy project to the ecosystem as group of libraries that draw heavily on `numpy` and several of its dependents such as `scipy`, `dask` and `sparse`
1. Under "Array libraries" as it provides tools for multi-dimensional data, that can be separated in signal and navigation dimensions
2. Under "Scientific Domains / Signal Processing" as the various HyperSpy extensions provide data analysis features for signals from a number of scientific domains, in particular from the realm of material sciences and electron microscopy

Add HyperSpy

---

content/en/_index.md
content/en/case-studies/blackhole-image.md
content/en/case-studies/cricket-analytics.md
content/en/case-studies/deeplabcut-dnn.md
content/en/case-studies/gw-discov.md
content/en/teams/index.md
content/en/user-survey-2020.md
content/ja/_index.md
content/ja/case-studies/blackhole-image.md
content/ja/case-studies/cricket-analytics.md
content/ja/case-studies/deeplabcut-dnn.md
content/ja/case-studies/gw-discov.md
content/ja/teams/index.md
content/ja/user-survey-2020.md
content/pt/_index.md
content/pt/case-studies/blackhole-image.md
content/pt/case-studies/cricket-analytics.md
content/pt/case-studies/deeplabcut-dnn.md
content/pt/case-studies/gw-discov.md
content/pt/teams/index.md
content/pt/user-survey-2020.md
netlify.toml

@steppi @rgommers FYI, this updates the grid and figure shortcodes.

Update theme (v0.15 and v0.14)

---

content/en/tabcontents.yaml

For consistency: Replace links to github repositories by those to documentation websites, where available.

Replace github by documentation links

---

content/en/news.md

This is important to show prominently, to give users a heads up so they can check whether their code is robust against the changes in 2.0.

Add a news entry about the 2.0 release date

---

layouts/partials/array-libraries.html
layouts/partials/data-science.html
layouts/partials/machine-learning.html
layouts/partials/visualization.html

this removes unnecessary bullet point from "ECOSYSTEM" sections.
e.g. before the change:
and after:

remove unnecessary single bullet point rendered under Ecosystem tabs

---

content/en/news.md

Announce the release of NumPy 2.0.0. Feel free to add references when they become available.

Announce NumPy 2.0.0

---

content/en/config.yaml

Removing the link to the NumPy Twitter/X account as a follow-up on the discussion in https://github.com/numpy/numpy.org/issues/765 and the [NumPy community call on July 31st, 2024](https://github.com/numpy/archive/blob/main/community_meetings/2024/community-2024-07-31.md).

Remove the link to the NumPy Twitter/X account

---

content/en/news.md

announce the NumPy 2.1.0 release

---

config.yaml.in
content/es/about.md
content/es/case-studies/blackhole-image.md
content/es/case-studies/cricket-analytics.md
content/es/case-studies/deeplabcut-dnn.md
content/es/case-studies/gw-discov.md
content/es/config.yaml
content/es/user-survey-2020.md

This PR enables Spanish translations and contributes some manual fixes to  #774. The numpy.org content was translated to Spanish within Crowdin, and typically manual adjustments are needed to get the documentation to build and render correctly.
The fixes here
1. Fix block quote shortcodes within case studies markdown files which were mangled by Crowdin
2. Untranslate some shortcode names and attributes which had accidentally been translated
3. Fix formatting of some figure shortcodes within case studies and the 2020 user survey.
4. Change the language name in the drop-down from the literally translated Inglés to Español.
cc @melissawm 
Some of these things are just due to Crowdin mangling the shortcodes, but I think we should also include in the translation documentation some guidelines …

Manual adjustments to numpy.org Spanish translations

---

content/es/config.yaml

This PR contributes fixes to internal links to #774. The links are currently to the English content instead of the Spanish content. This is something we should document for the translators (or we should find a way to have Crowdin adjust the links automatically and not suggest translators translate them).
cc @melissawm

Fix internal links for Spanish translations

---

crowdin.yml

This PR updates the crowdin.yml config file to account for the adjustment in the teams section from #734. Previously the structure was `content/xx/teams.md`, but now it is `content/xx/teams/index.md` and there are `toml` files within `content/xx/teams` for lists which are inserted into `/teams/index.md` with shortcodes.

Add teams subfolder to crowdin.yml

---

content/es/config.yaml

When navigating the Spanish version of the site, clicking the NumPy logo should bring the reader to the spanish-version home page.
Follow-up to #774

Redirect to spanish home page

---

assets/css/tabs.scss
content/es/tabcontents.yaml
content/ja/tabcontents.yaml
content/pt/tabcontents.yaml

This restores the display of the Scientific Domains tab for Japanese and Portuguese. An update of how these tabs are pulled together was not applied to the translated pages which was causing the missing content.
Also updates the CSS for the tabs so that the scientific domain titles are correctly aligned.
Finally, there were some newlines applies to yaml files that are probably incorrect.

Fix display of ecosystem tab for Ja and Pt

---

content/en/teams/index.md
content/en/teams/translations-team.toml

Hi all! This PR adds a "Translations team" section to the teams page. The toml file is manually added since translators are members of crowdin but not necessarily github.
I am happy to add links to github profiles and/or new avatars, just let me know. As a placeholder, folks without an avatar are showing up as the NumPy logo.
Closes #796

Add translations team

---

content/en/news.md

Fix date format in news.md

---

content/en/_index.md
content/es/_index.md
content/ja/_index.md
content/pt/_index.md

Remove dash from main page title

---

content/en/case-studies/deeplabcut-dnn.md

Updated two URLs in deeplabcut-dnn.md.
1. DeepLabCut model zoo
New link: https://deeplabcut.github.io/DeepLabCut/docs/ModelZoo.html
Old link does not work: http://www.mousemotorlab.org/dlc-modelzoo
2. DeepLabCut paper in Summary section
New link: https://static1.squarespace.com/static/57f6d51c9f74566f55ecf271/t/5eab5ff7999bf94756b27481/1588289532243/NathMathis2019.pdf
Old link does not work: http://orga.cvss.cc/wp-content/uploads/2019/05/NathMathis2019.pdf

Updated two URLs in deeplabcut-dnn.md

---

content/en/community.md

Updated links to SciPy Latin America and SciPy Japan
The correct links are:
SciPy Latin America: https://pythoncientifico.ar/
SciPy Japan: https://www.scipyjapan.scipy.org/

Updated links to SciPy Latin America and SciPy Japan

---

content/en/case-studies/blackhole-image.md
content/es/case-studies/blackhole-image.md
content/ja/case-studies/blackhole-image.md
content/pt/case-studies/blackhole-image.md

fix two URLs:
1. https://www.scipy.org -> https://scipy.org
this is just a redirect
2. https://pandas.io -> https://pandas.pydata.org
the second URL links to a spam website that has nothing to do with pandas Python package

fix two URLs

---

content/en/install.md

update the numpy installation page with tab based navigation 

---

content/en/learn.md

Update the link to Guide to NumPy (2015).
https://dl.acm.org/doi/10.5555/2886196
The old link does not work:
https://www.barnesandnoble.com/w/guide-to-numpy-travis-e-oliphant-phd/1144670472

DOC: Update the link to Guide to NumPy (2015)

---

content/en/tabcontents.yaml
content/es/tabcontents.yaml
content/ja/tabcontents.yaml
content/pt/tabcontents.yaml

project PyMC3 has been renamed to PyMC, update the website to reflect it.
See https://en.wikipedia.org/wiki/PyMC and https://www.pymc.io

rename PyMC3 to PyMC

---

content/en/about.md

Cc'ing the folks whose name is touched here for visibility: @ngoldbaum, @mhvk, @shoyer, @eric-wieser, @mtsokol, @HaoZeke. 
Welcome back to the steering council Marten, and welcome to the steering council Nathan! And a big thank you to Stephan and Eric for your contributions to NumPy's governance!

Update Steering Council and Institutional Partners membership

---

content/en/learn.md

Make the names accent consistent: Stefan -> Stéfan

DOC Make the name accents consistent

---

content/en/news.md

announce the NumPy 2.3.0 release
