numpy/numpy.org

index.rst
No need for that to be on the front page. 
We should add some new content soon, like link to governance docs and NumFOCUS.
=> MAINT: clean up some outdated/irrelevant links.

index.rst
fixes links , resolves numpy/numpy#10942
=> MAINT: fix broken links fixes numpy/numpy#10942

www/index.rst
=> ENH: donate via salsalabs

www/_templates/sitenav.html, www/community.rst, www/index.rst
Triggered by the question on the mailing list on donations. Also saw some more things to fix up urgently. Borrowed most of the community page from the pandas [community page](http://pandas.pydata.org/community.html).
=> Content improvements: donations, community, getting started

www/Makefile, www/community.rst, www/conf.py
I was reading the pages and noticed spelling error, so here's a fix + spell checker (no CI though).
=> Fix spelling + add spell checker

www/index.rst
All projects were asked to use the exact language in this PR.
=> Tweak donation language on request of NumFOCUS

config.yaml, layouts/partials/tabs.html
Wanted to open this for discussion, to see if these are the right headings/buckets to use or if people have better ideas.
Haven't found the time to write this content unfortunately.
=> Add names of "buckets" under Ecosystem on the front page

config.yaml, content/about.md, content/arraycomputing.md, content/community.md, content/install.md
Also clean up pages a little, and add an empty page for "array computing". Just making blank space to be filled ...
=> Add links to header and footer corresponding to sitemap.

config.yaml
Let's update the main navigation according to the approved sitemap (app.flowmapp.com/projects/84515/sitemap/).
=> Updating the navbar

layouts/partials/navbar-clone.html, layouts/partials/navbar.html
Demo URL: http://pr-69-numpy.org-newsite.surge.sh/
=> Navbar - Language tab - Help us to translate button added

.github/pull_request_template.md, .github/workflows/main.yml, README.md
- Push and PRs should trigger the work flow
=> Workflow trigger for master branch and minor change

.github/pull_request_template.md
Refer comments in https://github.com/numpy/numpy.org/pull/76
https://pr-77-scipy-sphinx-theme-v2.surge.sh
=> minor update in pull request template

config.yaml
=> Fixes gh-93 copy improvisations for In a Nutshell area on landing page

content/en/learn.md
=> Add a page title

content/en/arraycomputing.md
Fixed typo
https://pr-<120>-numpy.surge.sh
=> Ref #gh-94, typos fixed in arraycomputing tab using spell checker

config.yaml
1. Adding a link to the NumPy Roadmap.
2. Updating a link to the current Twitter account.
=> Update links in the footer

config.yaml, layouts/partials/section2.html
Fixes gh-138
http://numpy-<pr_number>.surge.sh/
=> Fixes link for license information using github license file Ref #gh_138

content/en/contribute.md
Closes gh-87
Note that the removed content was duplicate with the About Us page.
=> Finish Contribute page

content/en/gethelp.md, content/en/history.md
Uploading new content for gethelp.md and history.md.
=> Create gethelp.md and history.md

layouts/_default/baseof.html, layouts/_default/single.html
Removed loading icon and fade-in animation before each page loads.
For the front-page, there is a if-statement for the fade-in animation. It's currently set to false.
[Issue 101](https://github.com/numpy/numpy.org/issues/101)
=> Removed loading animations

config.yaml
Changing the formatting of the "Case Studies" section header to match the rest.
=> Change the formatting of the section header

layouts/partials/navbar-clone.html, layouts/partials/navbar.html
=> comments out language dropdown until translations are complete

.scripts/build.sh, .scripts/deploy.sh, .scripts/install.sh, .travis.yml, Dockerfile, README.md
Continuation of https://github.com/numpy/numpy.org/pull/146
As per the discussion: https://github.com/numpy/numpy.org/pull/146#issuecomment-581064436
http://numpy-166.surge.sh/
=> Travis re-setup - removed the docker 

config.yaml, layouts/partials/array-libraries.html, layouts/partials/css.html, static/css/section3.css, static/css/styles.css, static/css/tabs.css
=> Overrides the color for em elements set in uikit. All italics in black.

layouts/partials/footer.html, static/css/styles.css, static/js/app.js
=> adds mailchimp integration to footer email form

content/en/installing-python-and-numpy-guide.md
Quick fix for the hugo-fresh theme update. I thought this might be part of not running the submodule init, but I think this is a bug.
=> Fixes hugo loading error with updated theme

config.yaml, static/css/section2.css
Change to six tiles (works better for some screen widths, not 3 tiles on row 1 and 1 tile on row 2) and trim the text on each tile.
=> Improve the content and layout of the "Key Features" tiles.

layouts/partials/footer.html
=> Minor edit in the footer

content/en/about.md
Since we are inviting to visit the website, let's link to it as well.
=> Add a link to https://numfocus.org

content/en/community.md
Proofreading before the deployment.
=> Fix some errors in the text

content/en/press-kit.md
=> Update the link to the CoC

config.yaml, layouts/_default/baseof.html
Resolves #198. Attempted to test this, but I believe we'll need to test it at the numpy.org url.
=> Adds Google Analytics

content/en/code-of-conduct.md
For corresponding change in the main repo, see https://github.com/numpy/numpy/pull/16201
Note: please wait with merging till that PR to the main repo is merged first.
=> DOC: update members of the CoC committee

content/en/contribute.md
=> DOC: Fix developer guide link on /contribute page

layouts/partials/shell-lesson.html
Closes gh-240
The way it looks after this change:
I can to tweak the wording to not make it run off the screen, and change `exponential` to `normal` because it's shorter.
=> Make example in interactive shell copy-pastable

layouts/partials/array-libraries.html
Rewrote first sentence, trimmed rest of intro. Partly
brevity, partly because words like "newer" or "modern"
might not be clear.
=> DOC: Tighten ecosystem->array libraries

content/en/contribute.md
We have a designer working on the logo, so asking for new people to jump in there will be counterproductive. Still would love help with other aspects of graphic design of course.
=> Remove sentence about logo under "Graphic design" on Contributing page

layouts/partials/javascript.html, static/css/shell.css
Undo change in width of example in interactive shell. See gh-256 for details.
=> Update numpy version in interactive shell; fix example width

layouts/partials/footer.html, static/css/styles.css
=> Updates colors to Warm Black

static/css/styles.css
@rgommers, this fixes some weird padding I had missed in the footer to top-align everything
=> removes padding from p element in footer email

layouts/partials/tabs.html
=> Switch order of tabs - "scientific domains" first

content/en/contribute.md
We now have way more design talent than we ever had, so the removed sentence was no longer representative of our situation.
=> Another edit to graphic design request for contributions

config.yaml
Found more content with the serial comma.
=> Fix punctuation

content/en/learn.md
=> Fix link for the absolute beginners tutorial.

layouts/partials/array-libraries.html
Fixes gh-301
http://numpy-302.surge.sh/
=> tensor->xtensor

layouts/partials/scientific-domains.html
Partially addresses the issues from gh-295
1. Corrected the grammar - “bioinformatics” is in one word.
2. Switched "Bayesian Inference" and "Bioinformatics” to point at the correct packages.
=> Address the issues from gh-295

layouts/partials/scientific-domains.html
Fix reported bugs, add new entries for libraries we should have included
Closes gh-295
=> Improve "scientific domains" ecosystem figure.

layouts/partials/scientific-domains.html
Switching the images sd9.png and sd10.png to correctly illustrate the presented scientific domains.
=> Switch sd9.png and sd10.png

content/en/code-of-conduct.md
=> adds frontmatter alias for conduct.html from old numpy.org

layouts/partials/scientific-domains.html
Cloud computing is an important part of interactive computing. Binder seems like a good representative that goes well with jupyter. CC the maintainers @betatim @choldgraf @minrk @yuvipanda.
=> ecosystem: add binder to Interactive Computing?

layouts/partials/shell-content.html
Addresses comment on gh-316
Looks like this:
=> Add message to interactive shell about mybinder.org on launch

config.yaml, content/en/news.md
(after talking to @InessaPawson)
=> Survey end date will be dropped, so remove a mention of that

config.yaml
=> Update the meta tags

content/en/news.md
Updating the news article about the CZI grant.
=> Update the news article about the CZI grant 

content/en/press-kit.md
Updating the link to the folder with the new NumPy logo, minor changes to the text.
=> Update info about the logo

scripts/gallery/cache/numpy_team.context, scripts/gallery/numpy_team.yml, static/gallery/team.html
Adding @rossbar and @bjnath to the Docs team list. Fixes numpygh-349
=> Update the Docs team list

content/en/case-studies/deeplabcut-dnn.md
=> Update Prof Mathis affiliation in DeepLabCut case study

config.yaml
Fixes missing images when using Twitter cards (I hope)
=> Update params.images to fix Twitter Cards (and header meta data)

content/en/news.md
Add the latest 1.19.2 release and "prepare for python 3.9" news items
=> NEWS: add two news items

content/en/citing-numpy.md
I was surprised that the new numpy paper was not yet listed on the website, so I added it (and prettyfied the BibTeX code) 🙂
=> Add Harris et al. (2020) to suggested citations

layouts/partials/scientific-domains.html
Updating the link to PyQuil. Fixes gh-367.
=> Update the link to PyQuil

content/en/case-studies/blackhole-image.md
Edit for readability and clarity.
Some small fixes ("a 100", double-dash in the Bouman quote).
After editing:
=> DOC: Edit of Black Hole case study

content/en/learn.md, layouts/partials/footer.html, layouts/partials/javascript.html, layouts/shortcodes/numfocus.html, static/css/styles.css
Update the CDN link to Font Awesome and updates some of the icon classes so they'll render again.
Fixes the email newsletter form in the footer.
Removes text-decoration on the numfocus 'donate' button.
=> Fix Font Awesome Icons

.github/workflows/gh-pages.yml
=> Add CNAME during deployment to gh-pages

content/en/about.md
=> Trivial commit to redeploy

.github/workflows/gh-pages.yml
Let's try this, I think I had the `hugoVersion` in the wrong section of this template.
=> Move hugoVersion in Github Actions to correct job.

content/en/learn.md
Resolves #400 
Here's a preview:
=> Update Numpy Docs link in learn.md

crowdin.yml
For the format change, see https://support.crowdin.com/configuration-file/#ignoring-files-and-directories
=> Update crowdin.yml files to ignore, yml format change

content/en/install.md
Mostly to trigger Crowdin and see if the `crowdin.yml` changes took effect.
=> Minor textual tweak to the Install page content

layouts/partials/scientific-domains.html
=> Add two more projects to Chemistry in scientific domains tab

content/en/about.md
This follows the same change made in https://github.com/numpy/numpy/pull/18705
=> Update steering council members

config.yaml, config.yaml.in, content/pt/config.yaml
Some content is missing; the text in/around the interactive shell, and all content under the Ecosystem tab. ~I may be missing something but I don´t know where to find it...~ So I´ll mark this PR as a draft for now.
EDIT: it seems like the content under `layouts/partials` should be on crowdin.
=> Added translation of main page to Portuguese (Brazilian)

.github/workflows/gh-pages.yml
This is what I use locally, seems to work quite well.
=> Upgrade Hugo from 0.74 to 0.82

config.yaml.in, content/ja/config.yaml
Follow-up to gh-415
Now looks like:
=> Update Japanese language name in dropdown selector

layouts/partials/footer.html
=> Updates copyright year to 2021

gen_config.py
Described everything in  #443. 
You can refer to this link for more info: https://stackoverflow.com/questions/27092833/unicodeencodeerror-charmap-codec-cant-encode-characters
P.S -  I have used `io` because **it gives you backward compatibility with Python 2 as well.**
=> Resolved issue #443: UnicodeEncodeError

README.md
Resolves #445 
Updated Installations in ReadMe File, Added `python gen_config.py `
=> Updated Installations in ReadMe.md

config.yaml.in, content/en/config.yaml, content/en/tabcontents.yaml, content/ja/config.yaml, content/ja/tabcontents.yaml, content/pt/config.yaml, content/pt/tabcontents.yaml, gen_config.py, layouts/partials/array-libraries.html, layouts/partials/data-science.html, layouts/partials/machine-learning.html, layouts/partials/scientific-domains.html, layouts/partials/shell-content.html, layouts/partials/shell.html, layouts/partials/visualization.html
=> Shifting content to en/*.yaml files

content/en/news.md
Making an announcement about NumPy 1.21.0 release.
=> Make an announcement about NumPy 1.21.0 release

content/en/tabcontents.yaml
Fixes a few typos/formatting issues found during translation.
=> Fixes typos in tabcontents.yaml

content/en/config.yaml, content/en/news.md
Includes link to the full proposal and relevant Medium/press release links.
cc @rgommers
=> Added news item about CZI DEI grant

content/en/news.md
=> Fix typo in DEI grant news item title.

content/en/config.yaml, content/en/user-surveys.md, content/ja/config.yaml, content/pt/config.yaml
Creating user-surveys.md
Adding a link to /user-surveys.md in the footer. Fixes numpygh-477.
=> Create user-surveys.md. Add a link to it in the footer.

content/en/news.md
=> Announce the release of NumPy 1.22.0rc2.

content/en/news.md
=> Announce the NumPy 1.21.5 release.

content/en/news.md
Announce the release of NumPy 1.22.0.
=> Announce the NumPy 1.22.0 release.

content/en/case-studies/gw-discov.md
Change widely-separated to widely separated
=> Fix typo in gw-discov.md

README.md, netlify.toml
=> Set Python version globally

.github/workflows/gh-pages.yml, netlify.toml
=> Update hugo version

Makefile
=> Fixes #521 Makefile help for teams updated - minor

Makefile, README.md
=> Clean up Makefile

content/en/teams.md
Update the link to the list of the Steering Council members on teams.md
=> Update the link on teams.md

content/en/news.md
=> Announce NumPy 1.22.1 release.

netlify.toml
https://deploy-preview-541--numpy-org.netlify.app/reports/lighthouse
=> Add lighthouse to netlify

content/en/contribute.md
Removing duplicate text.  The TOC is in shortcuts.
=> Remove redundant table of contents

content/en/news.md
=> announce the NumPy 1.22.2 release

content/en/code-of-conduct.md, content/ja/code-of-conduct.md, content/pt/code-of-conduct.md
Mailing list message for reference:
https://mail.python.org/archives/list/numpy-discussion@python.org/thread/QYE4H72JMTNDGGCCVJ2Q6PZJUUIJZDOZ/#QYE4H72JMTNDGGCCVJ2Q6PZJUUIJZDOZ
=> Update CoC committee members: Rohit replaces Anirudh

netlify.toml
=> Tighten lighthouse thresholds

content/en/news.md
=> Announce the NumPy 1.22.3 release

content/en/news.md
Announcing the NumPy 1.21.6 release.
=> announce the NumPy 1.21.6 release

content/en/install.md, content/ja/install.md, content/pt/install.md
Fixes #571 by removing the sections about linux. Conda-forge now has gpu packages. Since the changes were all deletions, I took the liberty of modifying the translations as well, I hope it is appropriate. Along the way I made an opinionated edit to removed the recommendation to use the system libraries on linux since the versions lag way behind what is available on conda/PyPI.
=> simplify miniconda recommendations

.github/workflows/gh-pages.yml
=> Update GH actions

content/en/news.md
=> announce the NumPy 1.22.4 release

content/en/news.md
News update after the NumPy 1.23.0 release.
=> announce the NumPy 1.23.0 release

content/en/news.md
=> announce the NumPy 1.23.1 release.

netlify.toml
=> Upgrade lighthouse plugin

content/en/news.md
=> announce the NumPy 1.23.2 release

layouts/partials/scientific-domains.html
Adds PennyLane to the Quantum Computing column in `scientific-domains.html`.
PennyLane is a major package in quantum computing that depends on --- and heavily relies on functionality provided by --- NumPy.
Comparing the details of PennyLane to existing packages listed in the QC section:
Repository | Watchers | Forks | Stars
-- | -- | -- | --
https://github.com/PennyLaneAI/pennylane | 53 | 398 | 1.5k
https://github.com/rigetti/pyquil | 87 | 332 | 1.3k
https://github.com/qutip/qutip | 78 | 540 | 1.3k
https://github.com/Qiskit/qiskit/ | 99 | 743 | 2.7k
=> Add PennyLane to Quantum Computing column in scientific-domains.html 

content/en/news.md
=> announce the NumPy 1.23.3 release

layouts/partials/head.html
=> Update theme (uikit)

content/en/news.md
=> announce the NumPy 1.23.5 release

content/en/tabcontents.yaml
Added `Dagster` to ecosystem docs
=> Add Dagster to ecosystem docs

content/en/news.md
=> Announce the NumPy 1.24.0 release.

content/en/news.md
=> announce the NumPy 1.24.1 release

content/en/news.md
=> announce the NumPy 1.24.2 release

layouts/partials/scientific-domains.html
Fixes [gh-620](https://github.com/numpy/numpy.org/issues/620)
Added the Python package PyBaMM under the chemistry section in scientific domains tab of ecosystem.
=> Add a package to the ecosystem

content/en/news.md
Updating the news bar on the homepage with the latest news story from the NumPy team. 
Addresses https://github.com/numpy/numpy.org/issues/624.
=> Update the news bar

static/gallery/maintainers.html, static/gallery/triage-team.html
Mukulika has become a maintainer :tada:
=> move Mukulika from triage to maintainer

content/en/news.md
=> announce the NumPy 1.24.3 release

content/en/news.md
Announcing the NumPy 1.24.4 release.
=> announce the NumPy 1.24.4 release

content/en/news.md
=> announce the NumPy 1.25.1 release

content/en/news.md
=> Announce the NumPy 1.25.2 release.

.github/workflows/gh-pages.yml
I don't know how to serve the `/doc` subfolder with the GHA workflow yet.
=> Revert to uploading pages to numpy.github.com repo

content/pt/case-studies/blackhole-image.md, content/pt/config.yaml, content/pt/tabcontents.yaml
A few items on the website were missing pt-br translations.
cc @steppi
=> Add missing pt-br translations

content/en/news.md
=> Announce the NumPy 1.26.0 release

content/en/news.md
=> announce the NumPy 1.26.1 release

content/en/tabcontents.yaml, content/ja/tabcontents.yaml, content/pt/tabcontents.yaml
Fixes some broken links to the PyVista project's documentation
=> Fix PyVista links

content/en/news.md
=> announce the NumPy 1.26.2 release

content/en/config.yaml, content/ja/config.yaml, content/pt/config.yaml
=> Add navbar logo text

content/en/learn.md, content/ja/learn.md, content/pt/learn.md
Updating link and name to lecture notes.
=> Update link to lecture notes

netlify.toml
=> Update theme (v0.7)

content/en/news.md
=> announce the NumPy 1.26.3 release

static/gallery/docs-team.html, static/gallery/emeritus-maintainers.html, static/gallery/maintainers.html, static/gallery/survey-team.html, static/gallery/triage-team.html, static/gallery/web-team.html
=> Update gallery to new theme classes

content/en/news.md
=> announce the NumPy 1.26.4 release

netlify.toml
https://github.com/scientific-python/scientific-python-hugo-theme/blob/main/CHANGELOG.md
=> Update theme (v0.9)

netlify.toml
=> Update theme (v0.12)

netlify.toml
=> Update theme (v0.13)

content/en/case-studies/cricket-analytics.md
This doesn't change anything, but makes the format consistent with all the other figure shortcode calls.
So it will make it easier to update the figure shortcode call when we switch to using our own figure shortcode so that we can style figures using the PST styles.
=> Unify figure shortcode invocation

content/en/tabcontents.yaml
https://www.mail-archive.com/announce@apache.org/msg08917.html
=> remove references to mxnet which has been discontinued

content/en/tabcontents.yaml, content/ja/tabcontents.yaml, content/pt/tabcontents.yaml
=> pyjanitor link corrected

content/en/learn.md
=> replace the book with the latest 3rd edition link

content/en/tabcontents.yaml
=> Update link to CuPy website

content/en/install.md
=> Update install.md: fix broken links to Anaconda

content/en/learn.md
=> Update learn.md: fix links

content/en/config.yaml
This updates the latest release button to 2.0
=> Update latest release button

assets/css/custom.css, assets/css/mailchimp.css, layouts/partials/footer_actions.html, netlify.toml
=> Update theme (v0.18)

content/en/news.md
=> announce the NumPy 2.0.1 release

content/en/contribute.md
Add info about donating to NumPy to contribute.md
Resolves https://github.com/numpy/numpy.org/issues/498
Improve Fundraising section
=> Add info about donating to NumPy to contribute.md

netlify.toml
=> Update theme (v0.19)

content/en/news.md
=> announce the NumPy 2.0.2 release

content/en/news.md
=> announce the NumPy 2.1.1 release

content/es/_index.md, content/es/case-studies/gw-discov.md, content/es/contribute.md, content/es/teams/index.md
This PR updates #774 by cherry-picking the latest commits from #778 for Spanish translations, which were contributed by @OriolAbril (thank you!), and fixing some broken links.
cc @melissawm
=> L10n main es 2024 09 17 15 16 33

content/ja/config.yaml, content/pt/config.yaml
=> Fix display of ecosystem tab for Ja and Pt

content/en/news.md
=> announce the NumPy 2.1.2 release

content/en/news.md
=> announce the NumPy 2.1.3 release

netlify.toml
=> Update theme (v0.20)

content/en/news.md
=> announce the NumPy 2.2.0 release

netlify.toml
=> Use Python 3.13 on netlify

content/en/teams/translations-team.toml
Update link to @AtsushiSakai 's github profile. See See https://github.com/numpy/numpy.org/issues/55#issuecomment-2556911149
=> Update link in Translations team

content/en/news.md
=> announce the NumPy 2.2.1 release

netlify.toml
=> Update theme (v0.21)

content/en/news.md
=> Announce NumPy 2.2.2

content/en/config.yaml
Shortened NumPy YouTube link to: https://www.youtube.com/@NumPy_team .
Related to PR #808.
=> Shortened NumPy YouTube link in config.yaml

content/en/tabcontents.yaml, content/es/tabcontents.yaml, content/ja/tabcontents.yaml, content/pt/tabcontents.yaml
fix URL redirect http -> https
=> Update tabcontents.yaml fix URL redirect http -> https

content/en/news.md
=> Announce the NumPy 2.2.3 release

content/en/news.md
=> announce the NumPy 2.2.4 release

content/en/case-studies/cricket-analytics.md
Update the data graphing and visualization link to:
https://medium.com/data-science/advanced-sports-visualization-with-pandas-matplotlib-and-seaborn-9c16df80a81b
The original link no longer works.
https://towardsdatascience.com/advanced-sports-visualization-with-pandas-matplotlib-and-seaborn-9c16df80a81b
=> Remove a broken link in cricket-analytics.md

content/en/news.md
=> announce the NumPy 2.2.5 release

content/en/news.md
=> announce-numpy-2.2.6

content/en/config.yaml, content/en/news.md
Tweak front page for new release
=> tweak front page for new release

content/en/about.md
=> MAINT: Update toward the future

content/en/news.md
=> announce the NumPy 2.3.2 release

content/en/learn.md
Reopening PR #845 
Correct a typo in author name:
Jake Vanderplas -> Jake Vander**P**las
=> DOC Correct a typo in author name, merge conflict resolved

content/en/news.md
=> announce the NumPy 2.3.3 release
